version: '3.9'

services:
  postgres:
    image: postgres:11-alpine
    container_name: localhost
    environment:
      POSTGRES_DB: sop2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Можно добавить свой скрипт для инициализации базы данных

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sop2
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sop2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: always
